services:
  babydata:
    image: ${DOCKER_REGISTRY-}babydata
    build:
      context: .
      dockerfile: BabyData/Dockerfile
    depends_on:
      - firebirdsql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=firebirdsql;Database=/var/lib/firebird/data/babydata.fdb;User=SYSDBA;Password=masterkey
    volumes:
      - ./DataProtection_Keys:/home/app/.aspnet/DataProtection_Keys

  firebirdsql:
    image: ghcr.io/fdcastel/firebird:5.0.1-noble
    restart: always
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=petep
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=babydata.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - FIREBIRD_DATABASE_PAGE_SIZE=16384 
      - FIREBIRD_CONF_RemoteBindAddress=
    ports:
      - "3050:3050"
    volumes:
      - ./data:/var/lib/firebird/data