name: Docker

on:
  push
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          docker login --username petep --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./BabyData/Dockerfile . -t ghcr.io/petepeg/babydata:latest
          docker push ghcr.io/petepeg/babydata:latest
